FROM node:18.17.0 AS build

WORKDIR /app
COPY guess_game/frontend/package.json guess_game/frontend/package-lock.json ./

RUN npm install
ARG REACT_APP_BACKEND_URL=http://localhost:8080

COPY guess_game/frontend/ .
RUN REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL npm run build

FROM nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80 8080
CMD ["nginx", "-g", "daemon off;"]