name: trabalho-unidade-1

x-environment-backend: &default-backend-env
  FLASK_APP: "run.py"
  FLASK_DB_TYPE: "postgres"
  FLASK_DB_USER: "postgres"
  FLASK_DB_NAME: "postgres"
  FLASK_DB_PASSWORD: "secretpass"
  FLASK_DB_HOST: "postgres"
  FLASK_DB_PORT: "5432"

services:
  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network
    restart: always

  backend:
    image: matefreitasneto/backend:1.0.0
    environment:
      <<: *default-backend-env
    depends_on:
      - postgres
    networks:
      - backend-network
    deploy:
      replicas: 2
    restart: always

  frontend:
    image: matefreitasneto/frontend:1.0.3
    ports:
      - "8080:8080"
    networks:
      - backend-network
    restart: always

volumes:
  postgres_data:

networks:
  backend-network:
